# Generated by Django 5.1.15 on 2026-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EduArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=10, unique=True, verbose_name="编号"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("beginner", "小白入门"), ("advanced", "进阶提升")],
                        max_length=10,
                        verbose_name="梯队",
                    ),
                ),
                ("category", models.CharField(max_length=20, verbose_name="分类")),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                ("excerpt", models.CharField(max_length=200, verbose_name="摘要")),
                (
                    "read_time",
                    models.CharField(
                        default="5分钟", max_length=10, verbose_name="阅读时长"
                    ),
                ),
                (
                    "key_point",
                    models.CharField(max_length=200, verbose_name="核心要点"),
                ),
                ("body", models.TextField(blank=True, verbose_name="正文(HTML)")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "投教文章",
                "verbose_name_plural": "投教文章",
                "ordering": ["level", "order"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("industry", "行业要闻"),
                            ("notice", "公司公告"),
                            ("view", "观点解读"),
                        ],
                        max_length=10,
                        verbose_name="栏目",
                    ),
                ),
                ("tag", models.CharField(max_length=10, verbose_name="标签")),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                ("published_at", models.DateTimeField(verbose_name="发布时间")),
            ],
            options={
                "verbose_name": "市场资讯",
                "verbose_name_plural": "市场资讯",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=10, unique=True, verbose_name="编号"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("beginner", "小白入门"), ("advanced", "进阶提升")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                ("suit", models.CharField(max_length=120, verbose_name="适用人群")),
                (
                    "framework",
                    models.JSONField(default=list, verbose_name="策略框架(步骤列表)"),
                ),
                ("risk", models.CharField(max_length=300, verbose_name="风险点与局限")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "投资策略",
                "verbose_name_plural": "投资策略",
                "ordering": ["level", "order"],
            },
        ),
    ]
