# Generated by Django 5.1.15 on 2026-06-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FundManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="姓名")),
                (
                    "years",
                    models.PositiveIntegerField(default=1, verbose_name="从业年限"),
                ),
                (
                    "annual_return",
                    models.FloatField(default=0, verbose_name="任职年化回报(%)"),
                ),
                (
                    "funds_count",
                    models.PositiveIntegerField(default=1, verbose_name="在管基金数"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="简介")),
            ],
            options={
                "verbose_name": "基金经理",
                "verbose_name_plural": "基金经理",
            },
        ),
        migrations.CreateModel(
            name="MarketIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="指数名称")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="指数代码"
                    ),
                ),
                ("value", models.FloatField(verbose_name="最新点位")),
                ("change_pct", models.FloatField(verbose_name="涨跌幅(%)")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "大盘指数",
                "verbose_name_plural": "大盘指数",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="板块名称")),
                ("change_pct", models.FloatField(verbose_name="涨跌幅(%)")),
            ],
            options={
                "verbose_name": "热门板块",
                "verbose_name_plural": "热门板块",
                "ordering": ["-change_pct"],
            },
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="基金代码"
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="基金名称")),
                (
                    "ftype",
                    models.CharField(
                        choices=[
                            ("股票型", "股票型"),
                            ("混合型", "混合型"),
                            ("债券型", "债券型"),
                            ("指数型", "指数型"),
                            ("QDII", "QDII"),
                            ("货币型", "货币型"),
                            ("FOF", "FOF"),
                        ],
                        max_length=10,
                        verbose_name="基金类型",
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("R1", "R1"),
                            ("R2", "R2"),
                            ("R3", "R3"),
                            ("R4", "R4"),
                            ("R5", "R5"),
                        ],
                        max_length=2,
                        verbose_name="风险等级",
                    ),
                ),
                ("company", models.CharField(max_length=40, verbose_name="基金公司")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("宽基指数", "宽基指数"),
                            ("行业主题", "行业主题"),
                            ("债券固收", "债券固收"),
                            ("混合均衡", "混合均衡"),
                        ],
                        max_length=10,
                        verbose_name="投资方向",
                    ),
                ),
                (
                    "appetite",
                    models.JSONField(
                        default=list,
                        help_text="如 ['稳健','平衡']",
                        verbose_name="适配风险偏好",
                    ),
                ),
                ("scale", models.FloatField(verbose_name="规模(亿元)")),
                ("inception_date", models.DateField(verbose_name="成立日期")),
                ("nav", models.FloatField(verbose_name="单位净值")),
                ("acc_nav", models.FloatField(verbose_name="累计净值")),
                ("day_change", models.FloatField(verbose_name="日涨跌幅(%)")),
                (
                    "r_w1",
                    models.FloatField(blank=True, null=True, verbose_name="近1周(%)"),
                ),
                (
                    "r_m1",
                    models.FloatField(blank=True, null=True, verbose_name="近1月(%)"),
                ),
                (
                    "r_m3",
                    models.FloatField(blank=True, null=True, verbose_name="近3月(%)"),
                ),
                (
                    "r_m6",
                    models.FloatField(blank=True, null=True, verbose_name="近6月(%)"),
                ),
                (
                    "r_y1",
                    models.FloatField(blank=True, null=True, verbose_name="近1年(%)"),
                ),
                (
                    "r_y3",
                    models.FloatField(blank=True, null=True, verbose_name="近3年(%)"),
                ),
                (
                    "r_y5",
                    models.FloatField(blank=True, null=True, verbose_name="近5年(%)"),
                ),
                (
                    "r_since",
                    models.FloatField(blank=True, null=True, verbose_name="成立来(%)"),
                ),
                (
                    "rank_pct",
                    models.PositiveIntegerField(
                        default=50, verbose_name="同类排名前(%)"
                    ),
                ),
                ("mdd", models.FloatField(verbose_name="最大回撤(%)")),
                ("sharpe", models.FloatField(verbose_name="夏普比率")),
                ("vol", models.FloatField(verbose_name="年化波动率(%)")),
                ("down_risk", models.FloatField(default=0, verbose_name="下行风险(%)")),
                ("info_ratio", models.FloatField(default=0, verbose_name="信息比率")),
                ("tags", models.JSONField(default=list, verbose_name="特色标签")),
                (
                    "alloc_stock",
                    models.IntegerField(default=0, verbose_name="股票仓位(%)"),
                ),
                (
                    "alloc_bond",
                    models.IntegerField(default=0, verbose_name="债券仓位(%)"),
                ),
                (
                    "alloc_cash",
                    models.IntegerField(default=0, verbose_name="现金仓位(%)"),
                ),
                (
                    "fee_sub",
                    models.CharField(
                        default="", max_length=40, verbose_name="申购费率"
                    ),
                ),
                (
                    "fee_red",
                    models.CharField(
                        default="", max_length=40, verbose_name="赎回费率"
                    ),
                ),
                (
                    "fee_manage",
                    models.CharField(default="", max_length=40, verbose_name="管理费"),
                ),
                (
                    "fee_custody",
                    models.CharField(default="", max_length=40, verbose_name="托管费"),
                ),
                (
                    "fee_confirm",
                    models.CharField(
                        default="T+1", max_length=20, verbose_name="申购确认"
                    ),
                ),
                (
                    "fee_arrive",
                    models.CharField(
                        default="T+2", max_length=20, verbose_name="赎回到账"
                    ),
                ),
                (
                    "holdings",
                    models.JSONField(
                        default=list,
                        help_text="[[名称, 占比], ...]",
                        verbose_name="前十大重仓",
                    ),
                ),
                (
                    "industries",
                    models.JSONField(
                        default=list,
                        help_text="[[行业, 占比], ...]",
                        verbose_name="行业分布",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funds",
                        to="funds.fundmanager",
                        verbose_name="基金经理",
                    ),
                ),
            ],
            options={
                "verbose_name": "基金",
                "verbose_name_plural": "基金",
                "ordering": ["code"],
            },
        ),
    ]
