# Generated by Django 5.1.15 on 2026-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="姓名/称呼")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                (
                    "investor_type",
                    models.CharField(
                        choices=[("beginner", "理财小白"), ("advanced", "进阶基民")],
                        default="beginner",
                        max_length=10,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("getstarted", "新手入门咨询"),
                            ("product", "基金/产品咨询"),
                            ("strategy", "投资策略咨询"),
                            ("complaint", "投诉与建议"),
                            ("other", "其他"),
                        ],
                        default="getstarted",
                        max_length=20,
                        verbose_name="咨询主题",
                    ),
                ),
                ("message", models.TextField(verbose_name="咨询内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("done", "已回复"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="处理状态",
                    ),
                ),
                ("handle_note", models.TextField(blank=True, verbose_name="处理备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
            ],
            options={
                "verbose_name": "用户咨询",
                "verbose_name_plural": "用户咨询",
                "ordering": ["-created_at"],
            },
        ),
    ]
